name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: hookman
            asset_name: hookman-linux-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: hookman.exe
            asset_name: hookman-windows-amd64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: hookman
            asset_name: hookman-macos-amd64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: hookman
            asset_name: hookman-macos-arm64
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    - name: Build
      run: cargo build --release --target ${{ matrix.target }}
    
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./artifacts/**/*
        draft: false
        prerelease: false
        generate_release_notes: true